import ftplib
import os
import sys
from datetime import datetime

# Add current dir to path for config import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config

def recover_session(session_id):
    print(f"RECOVERING SESSION: {session_id}")
    print("=" * 60)
    
    # 1. Create placeholder HTML content
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vortex Pulse Verification Log - {session_id}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        body{{font-family:'Inter',sans-serif;background:#0f172a;color:#f8fafc;padding:2rem;margin:0;line-height:1.5;}}
        .container {{ max-width: 1000px; margin: 0 auto; }}
        .header {{ border-bottom: 2px dashed #334155; padding-bottom: 2rem; text-align: center; }}
        .status-box {{ background: #1e293b; border: 1px solid #38bdf8; padding: 2rem; border-radius: 0.75rem; margin-top: 2rem; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); }}
        h1 {{ font-weight: 700; color: #38bdf8; letter-spacing: -0.025em; margin-bottom: 0.5rem; }}
        .warning {{ color: #f43f5e; font-weight: 700; }}
        p {{ color: #94a3b8; font-size: 0.875rem; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Vortex Pulse - Audit Restoration</h1>
            <p>Session ID: {session_id}</p>
        </div>
        
        <div class="status-box">
            <p><span class="warning">NOTICE:</span> This verification log was manually recovered.</p>
            <p>The system has been re-synchronized. Future trading data for this session will appear here automatically as it occurs.</p>
            <p><strong>Status:</strong> Monitoring for next window settlement...</p>
            <p><strong>Last Sync:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        
        <p style="text-align:center; margin-top:50px; opacity:0.5;">
            Generated by Antigravity Recovery System v2.0
        </p>
    </div>
    <script>
        setTimeout(function() {{ location.reload(); }}, 60000);
    </script>
</body>
</html>"""

    # 2. Save locally
    lg_dir = os.path.join(os.path.dirname(__file__), "lg")
    session_dir = os.path.join(lg_dir, session_id)
    if not os.path.exists(session_dir):
        os.makedirs(session_dir, exist_ok=True)
    
    local_path = os.path.join(session_dir, "verification.html")
    with open(local_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"Created local placeholder: {local_path}")

    # 3. Upload to FTP
    try:
        print(f"Connecting to FTP: {config.FTP_HOST}...")
        ftp = ftplib.FTP(config.FTP_HOST)
        ftp.login(config.FTP_USER, config.FTP_PASS)
        ftp.cwd(config.FTP_ROOT)
        
        # Ensure remote directory exists
        try:
            ftp.mkd(session_id)
            print(f"Created remote directory: {session_id}")
        except:
            pass # Already exists
            
        ftp.cwd(session_id)
        
        # Upload as verification.html
        remote_filename = "verification.html"
        print(f"Uploading '{remote_filename}' to '{session_id}'...")
        with open(local_path, "rb") as f:
            ftp.storbinary(f"STOR {remote_filename}", f)
        
        print(f"Recovery upload COMPLETE: http://myfavoritemalshin.space/{session_id}/{remote_filename}")
        ftp.quit()
        
    except Exception as e:
        print(f"❌ FTP Error: {e}")

if __name__ == "__main__":
    target_session = "session_20260328_101642"
    recover_session(target_session)
